export const DATA_REQUEST = 'DATA_REQUEST';
export const DATA_FAILURE = 'DATA_FAILURE';
export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_HISTORY = 'GET_HISTORY';
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SHOW_FORM = 'SHOW_FORM';
